version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: UIS
      POSTGRES_DB: hoenn_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
    depends_on:
      - db
    command: python main.py

volumes:
  pgdata:
